DROP TABLE IF EXISTS STAGING_FARETAXI ;
DROP TABLE IF EXISTS FARE ;
----- CREATE TEMPORARY STAGING TABLE TO LOAD PARQUET FORMATTED DATA -----
CREATE EXTERNAL TABLE STAGING_FARETAXI
  USING parquet OPTIONS(path ':dataLocation/nyctaxifaredata_cleaned');
CREATE TABLE FARE USING column OPTIONS(buckets '11');
